FROM mcr.microsoft.com/devcontainers/universal:2.2.8-focal
# FROM node:19.7.0-bullseye
# FROM mcr.microsoft.com/devcontainers/typescript-node:18-bullseye

#RUN corepack enable \
#    && corepack prepare yarn@stable --activate \
#    && corepack enable yarn

WORKDIR /home

#CMD ["sleep", "365d"]
